package com.carpool.entity;

public enum NotificationType {
    NEW_BOOKING_REQUEST,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    PASSENGER_CANCELLATION,
    OWNER_RIDE_CANCELLATION,
    RIDE_COMPLETION,
    RIDE_POSTED,
    RATING_AVAILABLE,
    BOOKING_PENDING,
    RATING_RECEIVED,
    RIDE_CREATED,
    SUBSCRIPTION_PENDING,
    SUBSCRIPTION_PAYMENT_SUCCESS,
    SUBSCRIPTION_PAYMENT_FAILURE,
    KYC_VERIFICATION_RESULT
    ,
    TICKET_RAISED,
    TICKET_RESOLVED,
    BIRTHDAY_GREETING,
    GOVERNMENT_HOLIDAY_GREETING,
    REFERRAL_REGISTERED,
    REFERRAL_QUALIFIED,
    COIN_REWARD_CREDITED,
    REDEMPTION_SUBMITTED,
    REDEMPTION_APPROVED,
    REDEMPTION_REJECTED,
    SUBSCRIPTION_COINS_USED
}
