package com.carpool.entity;

public enum RegistrationStage {
    USER_TYPE_SELECTED,
    BASIC_DETAILS_COMPLETED,
    OTP_VERIFIED,
    DOCUMENT_VERIFIED,
    PROFILE_PHOTO_COMPLETED,
    SUBSCRIPTION_SELECTED,
    PAYMENT_SUBMITTED,
    REGISTRATION_COMPLETED
}
