ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INT;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS utr_number VARCHAR(80);
ALTER TABLE subscriptions MODIFY COLUMN status VARCHAR(40) NOT NULL;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS payment_date TIMESTAMP NULL;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP NULL;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS rejection_comment VARCHAR(500) NULL;